# Generated by Django 2.2 on 2021-07-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210721_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='body',
            field=models.TextField(default='lorem'),
            preserve_default=False,
        ),
    ]
