# Generated by Django 2.2 on 2021-07-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
